---
- name: Gather information from servers
  hosts: localhost
  gather_facts: no

  vars:
    servers:
      - name: server1
        public_dns: "54.152.152.58"
        username: "ec2-user"
        key_file: "/home/ec2-user/ec2_key.pem"
      - name: server2
        public_dns: "100.24.48.131"
        username: "ec2-user"
        key_file: "/home/ec2-user/ec2_key_2.pem"

  tasks:
    - name: Ensure output directory exists
      file:
        path: "./server_info"
        state: directory

    - name: Gather information from each server by connecting
      shell: >
        ssh -i "{{ item.key_file }}" {{ item.username }}@{{ item.public_dns }} << 'EOF'
        echo '############### Connecting to {{ item.name }} ###############'
        date
        hostname
        EOF
      loop: "{{ servers }}"
      register: server_output

    - name: Save output to file
      copy:
        content: "{{ item.stdout }}"
        dest: "./server_info/{{ item.item.name }}.txt"
      loop: "{{ server_output.results }}"
      when: item.stdout is defined

