---
- name: Ping and gather info from remote servers
  hosts: servers
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure output directory exists
      file:
        path: "./server_info1"
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Get hostname
      command: hostname
      register: hostname_output

    - name: Get current date
      command: date
      register: date_output

    - name: Ping the server
      ping:
      register: ping_output

    - name: Get password file contents
      command: cat /etc/passwd
      register: pass_output

    - name: Debug hostname_output
      debug:
        var: hostname_output

    - name: Debug date_output
      debug:
        var: date_output

    - name: Debug ping_output
      debug:
        var: ping_output

    - name: Debug pass_output
      debug:
        var: pass_output

    - name: Prepare output content
      set_fact:
        output_content: |
          Hostname: {{ hostname_output.stdout if hostname_output.stdout is defined else 'N/A' }}
          Date: {{ date_output.stdout if date_output.stdout is defined else 'N/A' }}
          Ping: {{ ping_output }}
          Password file: {{ pass_output.stdout if pass_output.stdout is defined else 'N/A' }}

    - name: Display the outputs
      debug:
        msg: "{{ output_content.split('\n') }}"

    - name: Save the output to local files
      copy:
        content: "{{ output_content }}"
        dest: "./server_info1/{{ ansible_host }}.txt"
      delegate_to: localhost

