---
- name: Gather information from multiple servers
  hosts: servers  # Reference the group defined in your inventory
  gather_facts: no

  tasks:
    - name: Ensure output directory exists
      file:
        path: "./server_info"
        state: directory

    - name: Gather information from each server by connecting
      shell: >
        ssh -i "{{ ansible_ssh_private_key_file }}" {{ ansible_user }}@{{ ansible_host }} << 'EOF'
        echo '############### Connecting to {{ inventory_hostname }} ###############'
        echo '################# switching to root #####################'
        sudo -i bash << 'SUDO_EOF'
        echo '#################### listing the password file content #####################'
        cat /etc/passwd
        echo '########################### displaying the date #########################'
        date
        echo '########################## displaying the hostname #######################'
        hostname
        SUDO_EOF
        EOF
      register: server_output

    - name: Debug server output
      debug:
        var: server_output

    - name: Save output to file
      copy:
        content: "{{ server_output.stdout }}"
        dest: "./server_info/{{ inventory_hostname }}.txt"
      when: server_output.stdout is defined

